[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm start"
restartPolicyType = "always"

[env]
# These will be set through Railway's environment variables interface
DISCORD_TOKEN = { default = "" }
CREATURE_CHANNEL_ID = { default = "" }
BOSS_CHANNEL_ID = { default = "" }
NODE_ENV = { default = "production" }
PORT = { default = "5000" }